package com.vodafone.frt.apis;

public enum ApiType {
    SEND_MSG_RESP,
    REFRESH_MSG, REGISTER_USER, BASE_MESSAGE, LOGIN, GET_USER_DETAILS, GET_SUBORDINATE_DETAILS, PAYLOAD_DATA, RECEIVE_MSG_RESP
}
